### ISSUE TITLE
Tool Installed but again asking for Installation

### ISSUE THREAD

**Issue by attacker34** [sethsec/celerystalk#121]
Hi @sethsec 

I've installed "celerystalk" on kali linux but after installation when i tried to run it:

```

root@Linux~/celerystalk# ./celerystalk
[!] To install celerystalk:
[!]   ./setup/install.sh


```

**Comment by attacker34** [comment]
I've used this solution from other ticket to tackle this issue.

```
In addition to what you have fixed so far, I had to run the following commands in the same order:

pip2 install celery==4.2.2
pip2 install -r setup/requirements.txt --upgrade

I think it's wise to use pip2 instead of pip in setup/install.sh while celerystalk is based on Python 2.x

```

**Comment by sethsec** [comment]
Thanks for this input @attacker34! I agree. I'm going to reopen this, and run it through some tests.

**Comment by sethsec** [comment]
This should be fixed now.  Seems to work with just the pip2 fix. If you think pinning celery to 4.2.2 is still needed, please let me know.
