### ISSUE TITLE
Supported services are not trimmed

### ISSUE THREAD

**Issue by cwaazywabbit** [sethsec/celerystalk#133]
```
[!] Nmap reports 10.35.100.202:1433 is running: [ms-sql-s]. There are no commands to run against ms-sql-s in config.ini
```
but in my config.ini
```
mssql = ms-sql, ms-sql-s
```
you see it, that little devilish space?

suggestion: after they are split, they should be trimmed.

**Comment by sethsec** [comment]
@cwaazywabbit - Thanks for this and all of the other issues. This one was easy, the others not as easy, but I look forward to getting to them!
