### ISSUE TITLE
Functionality to remove in-scope endpoints

### ISSUE THREAD

**Issue by Lisa-Fiander** [sethsec/celerystalk#136]
Hello, 

Is there any functionality within Celerystalk that can remove endpoints from scope?
After importing a new list to scope, my old endpoints are still in scope.
Thanks!

**Comment by sethsec** [comment]
Hey @Lisa-Fiander - You have two options.  If you don't want to keep your old date around, you can do an ./celerystalk admin reset and blow the whole database away.  

But the intended solution is to create another workspace: 

```
./celerystalk workspace create w- workspace_name -o /output/dir -m mode(vapt or bb) 
```
That way you can switch back and forth between workspaces as needed.

To find all workpace commands and help, try: 

```
./celerystalk workspace -h 
```

Let me know if that does the trick?

**Comment by Lisa-Fiander** [comment]
Hey @sethsec, thanks, _./celerystalk admin reset_ worked perfectly for what I am using it for right now.

Thanks!!
