### ISSUE TITLE
Add the ability to view the current work-spaces available.

### ISSUE THREAD

**Issue by Thurnun** [sethsec/celerystalk#22]
Feature Request:

Fantastic tool, though I noticed after walking away from it and coming back after a while, I forget the different work-spaces I was using.

I do not see an option to view the work-spaces that I had specified, this would be handy to have in such scenario.

**Comment by sethsec** [comment]
Thanks @Thurnun.  Great idea.  This is easy to do.  I should have something pushed to master in the next few days on this.

**Comment by sethsec** [comment]
done!
