### ISSUE TITLE
Additional Replacements in config.ini file

### ISSUE THREAD

**Issue by checkymander** [sethsec/celerystalk#40]
Some command line utilities support flags that change on a per-scan basis, but make scans more effective. Some additional replacement options that could be used in the config file.
[Cookies] : A string of cookies that can be passed to the underlying commands.
[OSType] : The operating system of the box you're targeting.
[DBType] : The underlying database to be scanned (in the event of SQLMAP usage)
[UA]         :  User Agent to pass with Web Requests.

**Comment by sethsec** [comment]
Nice idea @checkymander, thanks.  I think this will be straight forward to impliment, but I could be wrong.  :).  I'll let you know.

**Comment by checkymander** [comment]
If it's helpful I just created code that does something similar and seems pretty scalable.
I created a dict full of values (e.g.)
rep = {"__p1__":"value","__p2__","Value"}
and then use the following code to replace them inside the string.
     string="__p1__ replace this __p2__ and this"
     rep = dict((re.escape(k), v) for k, v in rep.items())
     pattern = re.compile("|".join(rep.keys()))
     for blah in placeyoustoredreplacements:
          string = pattern.sub(lambda m: rep[re.escape(m.group(0))], string)


Based on this code
https://stackoverflow.com/questions/6116978/how-to-replace-multiple-substrings-of-a-string

**Comment by sethsec** [comment]
Hey.  sethsec at gmail will do it!

**Comment by sethsec** [comment]
pushed to master!

**Comment by cwaazywabbit** [comment]
Just want to say that the `user-config` section is now a life-saver and allows complex yet flexible predefined scans.

Awesome job, Seth!
