### ISSUE TITLE
Baseline Config Issue - HTTP Scan

### ISSUE THREAD

**Issue by decidedlygray** [sethsec/celerystalk#43]
Using default settings for the `nmap_http_vuln` command, the following error happens on every host scanned:

```
PORT   STATE SERVICE VERSION
80/tcp open  http?
|_http-vuln-cve2014-3704: ERROR: Script execution failed (use -d to debug)
```

I think this could be fixed, and allow that Drupalgeddon scan to work, by adding the following to that command (lifted from the NSE script):
```
--script-args http-vuln-cve2014-3704.cmd="uname -a",http-vuln-cve2014-3704.uri="/drupal"
```

**Comment by sethsec** [comment]
Thanks for looking into this one. Should i just remove this from the default config?  or maybe update it with your syntax and remove it.  I mean qualys/openvas/nessus will all find Drupalgeddon, and I think anything else in an http-vuln NSE.    

I'm thinking that for a CTF/HTB/OSCP it might be useful, but for a VAPT, probably not.   

Thoughts?

**Comment by decidedlygray** [comment]
You're probably right about it being covered by the other scanners. I personally kind of like having it in there though. Double coverage never hurts, and I don't think this scan takes too long

**Comment by sethsec** [comment]
This is in the default config now in the dev branch. The nmap_http_vuln command is commented out by default now though, so if you need it, just enable it.  Thanks for the command improvement!  Keep them coming please!

**Comment by decidedlygray** [comment]
Thanks! I’ll `git pull` from dev before I launch my scans tonight.

I’ll circle back and close this once I’ve checked it out, or just feel free to close it and I’ll comment if there’s a problem.
