### ISSUE TITLE
"There are no workspaces yet" Help Screen Update

### ISSUE THREAD

**Issue by decidedlygray** [sethsec/celerystalk#56]
Just wanted to log this one: the `[!] There are no workspaces yet.` help message does not include the new `-m` in its help examples, which would be nice.

E.g.
```
root@kali:/opt/celerystalk# ./celerystalk scan

celerystalk  -	An asynchronous network enumeration/vulnerability scanner 
		Run all your tools against all your hosts (IPs/virtual hosts/subdomains)
		by @sethsec
		Build: 128

[!] There are no workspaces yet. Create one and run your command again:


./celerystalk workspace create -o output_dir                     #Default workspace
./celerystalk workspace create -o output_dir -w workspace_name   #Named workspace
```

**Comment by sethsec** [comment]
Thanks!  I noticed the same thing this evening. What do you think of this new one:

```
[!] There are no workspaces yet. Create one and run your command again:

./celerystalk workspace create -o output_dir -w workspace_name -m vapt
./celerystalk workspace create -o output_dir -w workspace_name -m bb
```

This would remove the guidance about the default workspace vs named workspace for the sake of brevity/ease, but would make it so you have to use the help or look at the readme to lean the concept of default vs named workspaces.  

this reason i think it is ok to leave out, is that now that i have the concept of current workspaces, i think there is really no reason to use the default workspace. thinking this will force people to name their workspaces, while giving you the option to use the default if you really want to.

**Comment by decidedlygray** [comment]
I like it. Or even condense it further:

```
./celerystalk workspace create -o output_dir -w workspace_name -m vapt_or_bb_mode
```
Either way though.
