### ISSUE TITLE
Error during setup and execution

### ISSUE THREAD

**Issue by decidedlygray** [sethsec/celerystalk#58]
I pulled the latest from the dev branch and I am seeing this error:

```
Traceback (most recent call last):
  File "../celerystalk", line 137, in <module>
    import lib.interactive
ImportError: No module named interactive
```

I'm wondering if the `interactive` module might not have been committed to git?

**Comment by sethsec** [comment]
you got it.  thanks for catching this.  i realized this sometime in the middle of night as well.  just pushed it to dev :)  thanks!
