### ISSUE TITLE
Bug on query summary: Cancelling Jobs Increases Submitted Count

### ISSUE THREAD

**Issue by decidedlygray** [sethsec/celerystalk#59]
I had a bunch of jobs (5266) queued and I cancelled them. Before cancelling them, the Submitted count was 15878. After cancelling the Submitted was 21144:

![image](https://user-images.githubusercontent.com/11695977/49059325-fc670600-f1cd-11e8-92b7-3a7bd579c3e6.png)

It looks like when `./celerystalk cancel all` gets executed, the count of cancelled jobs gets added to the Submitted jobs count

**Comment by sethsec** [comment]
My guess is that the discrepancy is the firefox-esr jobs aka post-processing jobs that got added when you cancelled all 5k remaining tasks.  here is the current workflow:

celerystalk wants to execute gobuster, so it creates a celery chain that:
* executes the initial task
* executes a post processing task that only gets submitted once the initial task has finished

So, this is what happens with the initial task:

* initial task/job gets called (gobuster for instance). 
* initial task creates entry in DB as pending
* initial task execute command (gobuster) and updates DB as running
* initial task sees that gobuster has finished updates DB as completed
* initial task ends

Now as soon as that initial task ends, celerystalk/celery creates the second post-processing task. 

The issue i think you saw is that the second task in the celery chain (the post processing task) does not get executed until queue is cleared up with ALL of the initial tasks,  As soon as there are less than 5 running tasks (0 pending), then you start to see all of the post processing commands (firefox-esr gobuster or firefox-esr photon).  

This is less obvious when you don't cancel anything (it is almost transparent... all you see is that the number of pending tasks starts to increase), but as you found out, it is confusing when you cancel stuff.

I think the solution is to move back away from chains and have the initial task call the post process function OUTSIDE of celery as part of the initial task.  but that would need a lot of testing.

**Comment by sethsec** [comment]
does that sound like what happend?   are tasks 15789-21144 all firefox commands?

**Comment by decidedlygray** [comment]
Sorry, I ended up dumping the environment because of another problem. I have no idea
