### ISSUE TITLE
[Feature Request] Make number of concurrent tasks user configurable

### ISSUE THREAD

**Issue by sethsec** [sethsec/celerystalk#65]
For the longest time i used concurrent=5 when starting celery.
However, on aws instance with only two CPU cores, this caused high load every once in a while. Note: This has never been an issue with virtual machines that have 4 CPU cores, and is only occasionally an issue even with 2 CPU cores.  

That said, I wanted to err on the safe side and made the change to remove the --concurrent option from celery start, which defaults to the number of concurrent tasks equals the number of CPU cores.  

So now, I want to give the user to ability to hardcode the number of concurrent tasks that celery will execute.

**Comment by sethsec** [comment]
Maybe something like this in the config:
[celery-config]
concurrent-threads = 5

[redis-config]
redis-port = 6379 

[celerystalk-config]
take-screenshots-automatically = yes

**Comment by cwaazywabbit** [comment]
Similar !40

**Comment by sethsec** [comment]
Pushed to master!
