### ISSUE TITLE
[OUTPUT].txt overwritten when mixing [VAPT/BB] with [URL Mode]

### ISSUE THREAD

**Issue by cwaazywabbit** [sethsec/celerystalk#66]
Hello Seth :)

When executing an initial scan and then add tasks by attempting to execute something like
```
./celerystalk scan -u http://10.10.10.10/secret_folder/
```
then some [OUTPUT].txt files are overwritten. This case would occur often when gobuster/proton detect new URLs that are worth looking into.

A dirty workaround would be appending something to [OUTPUT].

Cheers & Happy new year!

**Comment by sethsec** [comment]
Thanks for this Shadi. Great bug find, I should have realized this. I'll look into this shortly and push a fix!

**Comment by cwaazywabbit** [comment]
Hi,
so that it's also addressed, the same issue occurs when **only** using URL Mode multiple times with different URLs in the same workspace, which eventually overwrites previous [OUTPUT] files.

Regards

**Comment by sethsec** [comment]
Awesome.  Thanks and Noted!

**Comment by sethsec** [comment]
Pretty sure the fix is in scan.py on like 360. Something like this:

```
outfile = scan_output_base_file_dir + path  + _ + cmd_name
```

I'll try and last this tomorrow

**Comment by sethsec** [comment]
Sorry for the delay @cwaazywabbit .  Let me know if it works now?  Changes pushed to master.

**Comment by cwaazywabbit** [comment]
Sorry for being off the grid :)
I will let you know if it doesn't work, however, I doubt that and believe you will not be hearing from me ;-)

👍
