### ISSUE TITLE
Nmap output files not being saved

### ISSUE THREAD

**Issue by c-nagy** [sethsec/celerystalk#82]
Hello, first of all thanks for this great tool!

There's an issue with Nmap output not being saved when running `./celerystalk nmap`. Celerystalk is telling Nmap to write the output file two directories deep. 

![image](https://user-images.githubusercontent.com/3061769/57046335-611b0680-6c2d-11e9-8f0f-c7009cbedf26.png)

(TomTom is a public bug bounty)

 Nmap cannot create the subdirectory, which results in no saved Nmap output. Running the same command manually with a test host:

![image](https://user-images.githubusercontent.com/3061769/57046391-8f004b00-6c2d-11e9-8298-e2749c4724f4.png)

The services get populated into the `./celerystalk db services` table, but the raw Nmap output is nowhere to be found because of this issue.

Relevant section from my config.ini file

```
[nmap-commands]
; NOTE: ENABLE ONLY ONE tcp_scan entry
tcp_scan     : nmap [TARGET]  -n -sV -Pn
```
As a sidenote, it would be great to have full control over the Nmap commands from config.ini.  There appears to be some additional logic being applied outside of config.ini, for example the switch `-oN [OUTPUT]` is being added to the Nmap command even though it is not a part of the command in config.ini. I would prefer to have it be `-oA [OUTPUT]` but it appears I'd have to edit the lib/nmap.py file which isn't as clean as it could be ideally.

Anyway, thanks again for all the hard work. Celerystalk is a great time saver and is much appreciated :)

**Comment by sethsec** [comment]
@craig131 - Thanks so much for catching this bug, and thanks for your feedback.  I really appreciate it and it makes me really happy to know you find the project useful. 

I believe I have a fix for this. I'm going to push it to master now. Can you try it out when you have a moment?  

You are right about the nmap command. I should move the output options, and really all options out to the config. I wanted a way to make SURE that there are certain flags that are needed for celerystalk, but I can and should still give the user full control of the command and do some smarter checking to make sure the stuff I need is in that command.  

I'm going to leave that request in this ticket for now, but I plan on closing this issue out when you confirm the output is working, and moving the sidenote part to another issue (a feature request).
