### ISSUE TITLE
Only seems to do web enum

### ISSUE THREAD

**Issue by shifty0g** [sethsec/celerystalk#84]
so far i can only get this to do the http and https enumeration commands. 
I have tried using a custom config.ini ...even removing the http and https sections but they still seem to run. 

i would create a workspace, import my nmap scans then try do a scan celerstalk will still only do web checks. i have tried this on several target systems, config variants but out of ideas.  am i missing something here?

**Comment by sethsec** [comment]
Hey @shifty0g. Thanks for the bug. I fixed something like this in build 122. If you are running build 121 or older, can you update to latest build and try again? If you are on a recent build and still having the issue, can you let me know a few things: 

* What build number are you using (should be in banner)?
* What mode are you using (VAPT or BB)?
* Do you see the non http-services when you run ./celerystalk db services?
* Did you run the nmap command with the -sV flag?

Thanks!

**Comment by shifty0g** [comment]
Build 166

tried VAPT / BB

yea i see plenty of non http services


| 192.168.0.49 | 21    |   tcp    | ftp         |           vsftpd           |         2.3.4         |                                                   |
| 192.168.0.49 | 22    |   tcp    | ssh         |          OpenSSH           | 4.7p1 Debian 8ubuntu1 |                    protocol 2.0                   |
| 192.168.0.49 | 23    |   tcp    | telnet      |       Linux telnetd        |                       |                                                   |
| 192.168.0.49 | 25    |   tcp    | smtp        |       Postfix smtpd        |                       |                                                   |
| 192.168.0.49 | 53    |   tcp    | domain      |          ISC BIND          |         9.4.2         |                                                   |
| 192.168.0.49 | 80    |   tcp    | http        |        Apache httpd        |         2.2.8         |                   (Ubuntu) DAV/2                  |
| 192.168.0.49 | 111   |   tcp    | rpcbind     |                            |           2           |                    RPC #100000                    |
| 192.168.0.49 | 139   |   tcp    | netbios-ssn |         Samba smbd         |       3.X - 4.X       |                workgroup: WORKGROUP               |
| 192.168.0.49 | 445   |   tcp    | netbios-ssn |         Samba smbd         |     3.0.20-Debian     |                workgroup: WORKGROUP               |
| 192.168.0.49 | 512   |   tcp    | exec        |     netkit-rsh rexecd      |                       |                                                   |
| 192.168.0.49 | 513   |   tcp    | login       | OpenBSD or Solaris rlogind |                       |                                                   |
| 192.168.0.49 | 514   |   tcp    | shell       |                            |                       |                                                   |
| 192.168.0.49 | 1099  |   tcp    | java-rmi    |     Java RMI Registry      |                       |                                                   |
| 192.168.0.49 | 1524  |   tcp    | bindshell   | Metasploitable root shell  |                       |                                                   |
| 192.168.0.49 | 2049  |   tcp    | nfs         |                            |          2-4          |                    RPC #100003                    |
| 192.168.0.49 | 2121  |   tcp    | ftp         |          ProFTPD           |         1.3.1         |                                                   |
| 192.168.0.49 | 3306  |   tcp    | mysql       |           MySQL            |    5.0.51a-3ubuntu5   |                                                   |
| 192.168.0.49 | 3632  |   tcp    | distccd     |          distccd           |           v1          |        (GNU) 4.2.4 (Ubuntu 4.2.4-1ubuntu4)        |
| 192.168.0.49 | 5432  |   tcp    | postgresql  |       PostgreSQL DB        |     8.3.0 - 8.3.7     |                                                   |
| 192.168.0.49 | 5900  |   tcp    | vnc         |            VNC             |                       |                    protocol 3.3                   |
| 192.168.0.49 | 6000  |   tcp    | X11         |                            |                       |                   access denied                   |
| 192.168.0.49 | 6667  |   tcp    | irc         |         UnrealIRCd         |                       |                                                   |
| 192.168.0.49 | 6697  |   tcp    | irc         |         UnrealIRCd         |                       |                                                   |
| 192.168.0.49 | 8180  |   tcp    | unknown     |                            |                       |                                                   |
| 192.168.0.49 | 8787  |   tcp    | drb         |        Ruby DRb RMI        |                       |        Ruby 1.8; path /usr/lib/ruby/1.8/drb       |
| 192.168.0.49 | 34132 |   tcp    | status      |                            |           1           |                    RPC #100024                    |
| 192.168.0.49 | 36291 |   tcp    | mountd      |                            |          1-3          |                    RPC #100005                    |
| 192.168.0.49 | 50023 |   tcp    | java-rmi    |     Java RMI Registry      |                       |                                                   |
| 192.168.0.49 | 57549 |   tcp    | nlockmgr    |                            |          1-4          |                    RPC #100021                    |
| 192.168.0.50 | 21    |   tcp    | ftp         |          ProFTPD           |         1.3.1         |                                                   |
| 192.168.0.50 | 22    |   tcp    | ssh         |          OpenSSH           | 4.7p1 Debian 8ubuntu1 |                    protocol 2.0                   |
| 192.168.0.50 | 23    |   tcp    | telnet      |       Linux telnetd        |                       |                                                   |
| 192.168.0.50 | 25    |   tcp    | smtp        |       Postfix smtpd        |                       |                                                   |
| 192.168.0.50 | 53    |   tcp    | domain      |          ISC BIND          |         9.4.2         |                                                   |
| 192.168.0.50 | 80    |   tcp    | http        |        Apache httpd        |         2.2.8         | (Ubuntu) PHP/5.2.4-2ubuntu5.10 with Suhosin-Patch |
| 192.168.0.50 | 139   |   tcp    | netbios-ssn |         Samba smbd         |       3.X - 4.X       |                workgroup: WORKGROUP               |
| 192.168.0.50 | 445   |   tcp    | netbios-ssn |         Samba smbd         |     3.0.20-Debian     |                workgroup: WORKGROUP               |
| 192.168.0.50 | 3306  |   tcp    | mysql       |           MySQL            |    5.0.51a-3ubuntu5   |                                                   |
| 192.168.0.50 | 3632  |   tcp    | distccd     |          distccd           |           v1          |        (GNU) 4.2.4 (Ubuntu 4.2.4-1ubuntu4)        |
| 192.168.0.50 | 5432  |   tcp    | postgresql  |       PostgreSQL DB        |     8.3.0 - 8.3.7     |                                                   |
| 192.168.0.50 | 8009  |   tcp    | ajp13       |                            |                       |                                                   |
| 192.168.0.50 | 8180  |   tcp    | unknown     |                            |                       |                                                   |


I been using the following commands as part of another script to run my nmaps. the -sV is included on the TCP scan. These complete fine and import into celerystalk 

	#TCP 
	screen -L -Logfile "$outputdir"/nmap_tcp_full_$ip.log -d -m -S nmap-tcp-full-$ip nmap --stats-every 10s -Pn -vv -sSV -sC -A --script=default,version,banner,vuln --script-args=unsafe=1 -p0- -T4 --reason --excludefile "$excludesfile" $ip -oA "$outputdir"/nmap_tcp_full_$ip
	
	#UDP
    screen -L -Logfile "$outputdir"/nmap_udp_def_$ip.log -d -m -S nmap-udp-$ip nmap --stats-every 10s -Pn -vvv -sU -n --reason -T4 --excludefile "$excludesfile" $ip -oA "$outputdir"/nmap_udp_def_$ip

**Comment by sethsec** [comment]
Well the short answer is that, no, you are not missing something obvious. It is *supposed* to scan all of the services that are mapped in the config file. 

Are you always using a custom config with the -c flag, or does it also not work when you make changes to config.ini and don't specify a config with the -c flag? I ask because I don't use the -c flag very often, so it is possible there is a bug there. 

After writing a whole bunch of other stuff, I have another idea. The fact that it is still running http and http scans even though you removed them from the config makes me wonder if celery getting confused and not reading the config changes. If you don't mind starting over and losing the data in celerystalk, you can run: ```./celerystalk admin reset``` and then try to run the scan again with your modified config.ini

If you want to try a more pointed approach, try this (this is the relevant part of the ```admin reset``` command: 

```
pkill -f "celery"
rm ../*.pyc
rm ../lib/*.pyc
```

If none of that makes any difference, would you mind helping me out with a test against just one port to help make troubleshooting easier. 

cd to celerystalk directory
```bash
cp config.ini config.ini.bak
cp setup/config_default.ini config.ini
nmap 192.168.0.50 -p22 -sV -oX test.xml
./celerystalk workspace create -w test -o test -m bb
./celerystalk import -f test.xml
./celerystalk db services #to make sure port 22 shows up in this workspace
./celerystalk scan
```
Thanks again for the bug. I really appreciate you taking the time to report it!

**Comment by shifty0g** [comment]
i have tried with and without the -c flag

ok so i reset and cleared everything
done the nmap scan 
created the test workspace bb/vapt, done the nmap and imported it. when running scan i can see that ncrack nmap commands are being executed on port 22. so its working strictly on 22


I then did a full nmap -p0- 192.168.0.50 -oX test.xml and imported the results into the same workspace. running scan seemed to not do anything with it only showing finished from the previous port 22 commands despite importing more ports. db services shows all the ports including 22 but cant seem to start another scan once already run.
I then created another workspace test3 imported in the full ports ran scan but once again seeming to only do commands for the web ports. strange 



```

*************************************************************************************************************************************
                                    celerystalk Status | Workspace Name: test3  | CPU Load Avg: 0.7

                           Submitted: 16 | Queued: 0 | Running: 0 | Completed: 16  | Cancelled: 0  | Paused: 0
***************************************************************************************************************************************
[+] Completed Tasks (16) (Only showing last 5 when in brief mode):

  [Duration][    IP     ] command...
  [00:00:00][192.168.0.50] whatweb http://192.168.0.50:80 -a3 --colour=never > test3//192.168.0.50/celerystalkOutput/192.168.0.50_80...
  [00:00:01][192.168.0.50] gobuster -u http://192.168.0.50:80 -f -k -w /usr/share/seclists/Discovery/Web-Content/common.txt -s '200,...
  [00:00:00][192.168.0.50] wpscan --url http://192.168.0.50:80 --disable-tls-checks --no-banner -f cli-no-color --enumerate p t tt u...
  [00:00:08][192.168.0.50] firefox-esr gobuster-screenshots | 192.168.0.50 | test3/celerystalkReports/screens/192.168.0.50_8180_tcp
  [00:00:04][192.168.0.50] firefox-esr gobuster-screenshots | 192.168.0.50 | test3/celerystalkReports/screens/192.168.0.50_80_tcp
  +11 more rows

[+] FIN! All submitted jobs in this workspace have finished.
```



i then created another workspace and did an nmap scan excluding out web port

nmap -p21,22,23,25,53,139,445,3306,3632,5432 -sV 192.168.0.50 -oX test2.xml
./celerystalk workspace create -w test4 -o test4 -m vapt
./celerystalk import -f test2.xml 
./celerystalk db services 
```

[+] Showing services for the [test4] workspace

+--------------+------+----------+-------------+---------------+-----------------------+-------------------------------------+
| IP           | Port | Protocol | Service     |    Product    |        Version        |              Extra Info             |
+--------------+------+----------+-------------+---------------+-----------------------+-------------------------------------+
| 192.168.0.50 | 21   |   tcp    | ftp         |    ProFTPD    |         1.3.1         |                                     |
| 192.168.0.50 | 22   |   tcp    | ssh         |    OpenSSH    | 4.7p1 Debian 8ubuntu1 |             protocol 2.0            |
| 192.168.0.50 | 23   |   tcp    | telnet      | Linux telnetd |                       |                                     |
| 192.168.0.50 | 25   |   tcp    | smtp        | Postfix smtpd |                       |                                     |
| 192.168.0.50 | 53   |   tcp    | domain      |    ISC BIND   |         9.4.2         |                                     |
| 192.168.0.50 | 139  |   tcp    | netbios-ssn |   Samba smbd  |       3.X - 4.X       |         workgroup: WORKGROUP        |
| 192.168.0.50 | 445  |   tcp    | netbios-ssn |   Samba smbd  |       3.X - 4.X       |         workgroup: WORKGROUP        |
| 192.168.0.50 | 3306 |   tcp    | mysql       |     MySQL     |    5.0.51a-3ubuntu5   |                                     |
| 192.168.0.50 | 3632 |   tcp    | distccd     |    distccd    |           v1          | (GNU) 4.2.4 (Ubuntu 4.2.4-1ubuntu4) |
| 192.168.0.50 | 5432 |   tcp    | postgresql  | PostgreSQL DB |     8.3.0 - 8.3.7     |                                     |
+--------------+------+----------+-------------+---------------+-----------------------+-------------------------------------+

```
./celerystalk scan


```
***************************************************************************************************************************************
                                    celerystalk Status | Workspace Name: test4  | CPU Load Avg: 0.2

                           Submitted: 0 | Queued: 0 | Running: 0 | Completed: 0  | Cancelled: 0  | Paused: 0
***************************************************************************************************************************************
[!] There are no running tasks in this workspace. Did you want another workspace
```

so strange now it doesnt seem to be aware of the ports. only when there is web ports it will do anything but strictly one them
